### ISSUE TITLE
Usage of deltaTime triggers no-undef rule

### ISSUE THREAD

**Issue by StarLederer** [marksherman/eslint-plugin-p5js#2]
[deltaTime](https://p5js.org/reference/#/p5/deltaTime) is a global read-only variable that stores the time since the last drawn frame in milliseconds and is used for framerate-independent motion. Eslint thinks it is undefined.

I think it has to be added to p5.base in [index.js](https://github.com/marksherman/eslint-plugin-p5js/blob/master/lib/index.js)

**Comment by marksherman** [comment]
yup, yes it does! Great catch. Thank you.
